/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TournamentsRouteImport } from './routes/tournaments'
import { Route as TournamentRouteImport } from './routes/tournament'
import { Route as JoinRouteImport } from './routes/join'
import { Route as HowToUseRouteImport } from './routes/how-to-use'
import { Route as CreateRouteImport } from './routes/create'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WatchCodeRouteImport } from './routes/watch.$code'
import { Route as TournamentsSlugRouteImport } from './routes/tournaments.$slug'
import { Route as PlayCodeRouteImport } from './routes/play.$code'
import { Route as ManageCodeRouteImport } from './routes/manage.$code'
import { Route as TournamentsSlugManageRouteImport } from './routes/tournaments.$slug.manage'
import { Route as TournamentsSlugTeamsTeamIdRouteImport } from './routes/tournaments.$slug.teams.$teamId'
import { Route as TournamentsSlugPlayersPlayerIdRouteImport } from './routes/tournaments.$slug.players.$playerId'

const TournamentsRoute = TournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentRoute = TournamentRouteImport.update({
  id: '/tournament',
  path: '/tournament',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToUseRoute = HowToUseRouteImport.update({
  id: '/how-to-use',
  path: '/how-to-use',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchCodeRoute = WatchCodeRouteImport.update({
  id: '/watch/$code',
  path: '/watch/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsSlugRoute = TournamentsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TournamentsRoute,
} as any)
const PlayCodeRoute = PlayCodeRouteImport.update({
  id: '/play/$code',
  path: '/play/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageCodeRoute = ManageCodeRouteImport.update({
  id: '/manage/$code',
  path: '/manage/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsSlugManageRoute = TournamentsSlugManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => TournamentsSlugRoute,
} as any)
const TournamentsSlugTeamsTeamIdRoute =
  TournamentsSlugTeamsTeamIdRouteImport.update({
    id: '/teams/$teamId',
    path: '/teams/$teamId',
    getParentRoute: () => TournamentsSlugRoute,
  } as any)
const TournamentsSlugPlayersPlayerIdRoute =
  TournamentsSlugPlayersPlayerIdRouteImport.update({
    id: '/players/$playerId',
    path: '/players/$playerId',
    getParentRoute: () => TournamentsSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/how-to-use': typeof HowToUseRoute
  '/join': typeof JoinRoute
  '/tournament': typeof TournamentRoute
  '/tournaments': typeof TournamentsRouteWithChildren
  '/manage/$code': typeof ManageCodeRoute
  '/play/$code': typeof PlayCodeRoute
  '/tournaments/$slug': typeof TournamentsSlugRouteWithChildren
  '/watch/$code': typeof WatchCodeRoute
  '/tournaments/$slug/manage': typeof TournamentsSlugManageRoute
  '/tournaments/$slug/players/$playerId': typeof TournamentsSlugPlayersPlayerIdRoute
  '/tournaments/$slug/teams/$teamId': typeof TournamentsSlugTeamsTeamIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/how-to-use': typeof HowToUseRoute
  '/join': typeof JoinRoute
  '/tournament': typeof TournamentRoute
  '/tournaments': typeof TournamentsRouteWithChildren
  '/manage/$code': typeof ManageCodeRoute
  '/play/$code': typeof PlayCodeRoute
  '/tournaments/$slug': typeof TournamentsSlugRouteWithChildren
  '/watch/$code': typeof WatchCodeRoute
  '/tournaments/$slug/manage': typeof TournamentsSlugManageRoute
  '/tournaments/$slug/players/$playerId': typeof TournamentsSlugPlayersPlayerIdRoute
  '/tournaments/$slug/teams/$teamId': typeof TournamentsSlugTeamsTeamIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/how-to-use': typeof HowToUseRoute
  '/join': typeof JoinRoute
  '/tournament': typeof TournamentRoute
  '/tournaments': typeof TournamentsRouteWithChildren
  '/manage/$code': typeof ManageCodeRoute
  '/play/$code': typeof PlayCodeRoute
  '/tournaments/$slug': typeof TournamentsSlugRouteWithChildren
  '/watch/$code': typeof WatchCodeRoute
  '/tournaments/$slug/manage': typeof TournamentsSlugManageRoute
  '/tournaments/$slug/players/$playerId': typeof TournamentsSlugPlayersPlayerIdRoute
  '/tournaments/$slug/teams/$teamId': typeof TournamentsSlugTeamsTeamIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/how-to-use'
    | '/join'
    | '/tournament'
    | '/tournaments'
    | '/manage/$code'
    | '/play/$code'
    | '/tournaments/$slug'
    | '/watch/$code'
    | '/tournaments/$slug/manage'
    | '/tournaments/$slug/players/$playerId'
    | '/tournaments/$slug/teams/$teamId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/how-to-use'
    | '/join'
    | '/tournament'
    | '/tournaments'
    | '/manage/$code'
    | '/play/$code'
    | '/tournaments/$slug'
    | '/watch/$code'
    | '/tournaments/$slug/manage'
    | '/tournaments/$slug/players/$playerId'
    | '/tournaments/$slug/teams/$teamId'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/how-to-use'
    | '/join'
    | '/tournament'
    | '/tournaments'
    | '/manage/$code'
    | '/play/$code'
    | '/tournaments/$slug'
    | '/watch/$code'
    | '/tournaments/$slug/manage'
    | '/tournaments/$slug/players/$playerId'
    | '/tournaments/$slug/teams/$teamId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  HowToUseRoute: typeof HowToUseRoute
  JoinRoute: typeof JoinRoute
  TournamentRoute: typeof TournamentRoute
  TournamentsRoute: typeof TournamentsRouteWithChildren
  ManageCodeRoute: typeof ManageCodeRoute
  PlayCodeRoute: typeof PlayCodeRoute
  WatchCodeRoute: typeof WatchCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tournaments': {
      id: '/tournaments'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof TournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournament': {
      id: '/tournament'
      path: '/tournament'
      fullPath: '/tournament'
      preLoaderRoute: typeof TournamentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-use': {
      id: '/how-to-use'
      path: '/how-to-use'
      fullPath: '/how-to-use'
      preLoaderRoute: typeof HowToUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$code': {
      id: '/watch/$code'
      path: '/watch/$code'
      fullPath: '/watch/$code'
      preLoaderRoute: typeof WatchCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$slug': {
      id: '/tournaments/$slug'
      path: '/$slug'
      fullPath: '/tournaments/$slug'
      preLoaderRoute: typeof TournamentsSlugRouteImport
      parentRoute: typeof TournamentsRoute
    }
    '/play/$code': {
      id: '/play/$code'
      path: '/play/$code'
      fullPath: '/play/$code'
      preLoaderRoute: typeof PlayCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/$code': {
      id: '/manage/$code'
      path: '/manage/$code'
      fullPath: '/manage/$code'
      preLoaderRoute: typeof ManageCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$slug/manage': {
      id: '/tournaments/$slug/manage'
      path: '/manage'
      fullPath: '/tournaments/$slug/manage'
      preLoaderRoute: typeof TournamentsSlugManageRouteImport
      parentRoute: typeof TournamentsSlugRoute
    }
    '/tournaments/$slug/teams/$teamId': {
      id: '/tournaments/$slug/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/tournaments/$slug/teams/$teamId'
      preLoaderRoute: typeof TournamentsSlugTeamsTeamIdRouteImport
      parentRoute: typeof TournamentsSlugRoute
    }
    '/tournaments/$slug/players/$playerId': {
      id: '/tournaments/$slug/players/$playerId'
      path: '/players/$playerId'
      fullPath: '/tournaments/$slug/players/$playerId'
      preLoaderRoute: typeof TournamentsSlugPlayersPlayerIdRouteImport
      parentRoute: typeof TournamentsSlugRoute
    }
  }
}

interface TournamentsSlugRouteChildren {
  TournamentsSlugManageRoute: typeof TournamentsSlugManageRoute
  TournamentsSlugPlayersPlayerIdRoute: typeof TournamentsSlugPlayersPlayerIdRoute
  TournamentsSlugTeamsTeamIdRoute: typeof TournamentsSlugTeamsTeamIdRoute
}

const TournamentsSlugRouteChildren: TournamentsSlugRouteChildren = {
  TournamentsSlugManageRoute: TournamentsSlugManageRoute,
  TournamentsSlugPlayersPlayerIdRoute: TournamentsSlugPlayersPlayerIdRoute,
  TournamentsSlugTeamsTeamIdRoute: TournamentsSlugTeamsTeamIdRoute,
}

const TournamentsSlugRouteWithChildren = TournamentsSlugRoute._addFileChildren(
  TournamentsSlugRouteChildren,
)

interface TournamentsRouteChildren {
  TournamentsSlugRoute: typeof TournamentsSlugRouteWithChildren
}

const TournamentsRouteChildren: TournamentsRouteChildren = {
  TournamentsSlugRoute: TournamentsSlugRouteWithChildren,
}

const TournamentsRouteWithChildren = TournamentsRoute._addFileChildren(
  TournamentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  HowToUseRoute: HowToUseRoute,
  JoinRoute: JoinRoute,
  TournamentRoute: TournamentRoute,
  TournamentsRoute: TournamentsRouteWithChildren,
  ManageCodeRoute: ManageCodeRoute,
  PlayCodeRoute: PlayCodeRoute,
  WatchCodeRoute: WatchCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
