/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as JoinRouteImport } from './routes/join'
import { Route as CreateRouteImport } from './routes/create'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WatchCodeRouteImport } from './routes/watch.$code'
import { Route as PlayCodeRouteImport } from './routes/play.$code'
import { Route as ManageCodeRouteImport } from './routes/manage.$code'

const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchCodeRoute = WatchCodeRouteImport.update({
  id: '/watch/$code',
  path: '/watch/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayCodeRoute = PlayCodeRouteImport.update({
  id: '/play/$code',
  path: '/play/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageCodeRoute = ManageCodeRouteImport.update({
  id: '/manage/$code',
  path: '/manage/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/join': typeof JoinRoute
  '/manage/$code': typeof ManageCodeRoute
  '/play/$code': typeof PlayCodeRoute
  '/watch/$code': typeof WatchCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/join': typeof JoinRoute
  '/manage/$code': typeof ManageCodeRoute
  '/play/$code': typeof PlayCodeRoute
  '/watch/$code': typeof WatchCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/join': typeof JoinRoute
  '/manage/$code': typeof ManageCodeRoute
  '/play/$code': typeof PlayCodeRoute
  '/watch/$code': typeof WatchCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/join'
    | '/manage/$code'
    | '/play/$code'
    | '/watch/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/join'
    | '/manage/$code'
    | '/play/$code'
    | '/watch/$code'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/join'
    | '/manage/$code'
    | '/play/$code'
    | '/watch/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  JoinRoute: typeof JoinRoute
  ManageCodeRoute: typeof ManageCodeRoute
  PlayCodeRoute: typeof PlayCodeRoute
  WatchCodeRoute: typeof WatchCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$code': {
      id: '/watch/$code'
      path: '/watch/$code'
      fullPath: '/watch/$code'
      preLoaderRoute: typeof WatchCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$code': {
      id: '/play/$code'
      path: '/play/$code'
      fullPath: '/play/$code'
      preLoaderRoute: typeof PlayCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/$code': {
      id: '/manage/$code'
      path: '/manage/$code'
      fullPath: '/manage/$code'
      preLoaderRoute: typeof ManageCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  JoinRoute: JoinRoute,
  ManageCodeRoute: ManageCodeRoute,
  PlayCodeRoute: PlayCodeRoute,
  WatchCodeRoute: WatchCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
